const notices = [
  {
    id: '1',
    name: 'cat',
    petImg: 'https://placehold.co/280x288/orange/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'kiiv',
    age: 'one year',
    price: '1$',
    category: 'sell',
  },
  {
    id: '2',
    name: 'dog',
    petImg: 'https://placehold.co/280x288/tomato/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '2$',
    category: 'lost/found',
  },
  {
    id: '3',
    name: 'cat',
    petImg: 'https://placehold.co/280x288/tomato/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '3$',
    category: 'lost/found',
  },
  {
    id: '4',
    name: 'dog',
    petImg: 'https://placehold.co/280x288/orange/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '4$',
    category: 'lost/found',
  },
  {
    id: '5',
    name: 'cat',
    petImg: 'https://placehold.co/280x288/orange/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '5$',
    category: 'sell',
  },
  {
    id: '6',
    name: 'dog',
    petImg: 'https://placehold.co/280x288/orange/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '6$',
    category: 'in good hands',
  },
  {
    id: '7',
    name: 'cat',
    petImg: 'https://placehold.co/280x288/orange/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '7$',
    category: 'in good hands',
  },
  {
    id: '8',
    name: 'dog',
    petImg: 'https://placehold.co/280x288/orange/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '8$',
    category: 'sell',
  },
  {
    id: '9',
    name: 'dog',
    petImg: 'https://placehold.co/280x288/orange/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '9$',
    category: 'sell',
  },
  {
    id: '10',
    name: 'cat',
    petImg: 'https://placehold.co/280x288/orange/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '10$',
    category: 'sell',
  },
  {
    id: '11',
    name: 'dog',
    petImg: 'https://placehold.co/280x288/orange/white',
    title: 'Сute dog looking for a home',
    breed: 'Pomeranian',
    place: 'Lviv',
    age: 'one year',
    price: '11$',
    category: 'sell',
  },
];

const getNotices = (category, name) => {
  const result = notices.filter(
    notice => notice.category === category && notice.name === name
  );
  return result;
};

export default getNotices;
// export const getProductById = productId => {
//   return products.find(product => product.id === productId);
// };
